modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/spacemex/Todo/issues"
license = "MIT"
clientSideOnly = true

[[mods]]
modId = "todo"
version = "${version}"
displayName = "Todo"
authors = "Space_Mex"
description = '''
Simple Configurable Todo Mod
'''
#logoFile = ""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/todo"

[[dependencies.todo]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.todo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.todo]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
